#!/bin/sh

# D-bus
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
       eval `dbus-launch --sh-syntax --exit-with-session`
fi

export OOO_FORCE_DESKTOP=gnome &
nitrogen --restore &
#bmpanel Dusk &
